RSVPSite/Controllers/AttendeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;
using Cts.HR.Recruiting.RSVP.Models;
using Cts.HR.Recruiting.RSVP.ViewModels;
using System.Web.Configuration;

namespace Cts.HR.Recruiting.RSVP.Controllers
{
   [Authorize]
    public class AttendeeController : Controller
    {
        private RSVPDBContext db = new RSVPDBContext();

        //
        // GET: /Attendee/

        public ActionResult Index(int? id)
        {
           //get event id list attendees
           var m = db.Events.Where(e => e.Id == id).Include(a => a.Attendees).FirstOrDefault();
           List<Attendee> model = new List<Attendee>(m.Attendees);
            return View(model);
        }

        //
        // GET: /Attendee/Excel/2

        //public ExcelResult Excel(int? id)
        public ActionResult Excel(int? id)
        {
            var attendees = db.Attendee.Where(a => a.EventId == id)
                .ToList()
                .Select(attendee => string.Format("{0},{1},{2},{3}", attendee.FirstName, attendee.LastName, attendee.Email, attendee.Phone));

            var csvString = string.Join(Environment.NewLine, attendees.ToArray());
            var bytes = System.Text.Encoding.ASCII.GetBytes(csvString);
            return File(bytes, "application/xls", db.Events.Single(a => a.Id == id).Name + " - Attendees.csv");

           }


        //
        // GET: /Attendee/Details/5

        public ActionResult Details(int id = 0)
        {
           //TODO: fix back to list action link on view
           //TODO: fix layout of view
           
           //pass attendee with event to display custom questions
           //RegisterData rd = new RegisterData
           //{
           //   Attendee = db.Attendee.Include(e => e.Answer).Include(e => e.Event).SingleOrDefault(a => a.Id == id)
           //};




           Attendee Attendee = db.Attendee.Include(e => e.Answer).Include(e => e.Event).SingleOrDefault(a => a.Id == id);
            if (Attendee == null)
            {
                return HttpNotFound();
            }
            return View(Attendee);
        }

        //register for event
        // GET: /Attendee/Create
       [AllowAnonymous]
        public ActionResult Create(int id = 0)
        {
          //displaytemplate
           var regData = new RegisterData
           {
              //Event = db.Events.Include(e => e.CustomQuestions).SingleOrDefault(e => e.Id == id)
              Event = db.Events.Find(id)
           };
            return View(regData);
        }

        //
        // POST: /Attendee/Create

        [HttpPost]
       [AllowAnonymous]
        public ActionResult Create(RegisterData regData)
       {          
          string ukey = RandomKey();
            regData.Attendee.UserKey = ukey;

            regData.Attendee.EventId = regData.Event.Id;
            var errors = ModelState.Values.Where(a => a.Errors.Any());
            if (ModelState.IsValid)
            {
               //regData.Responses.ForEach(r => regData.Attendee.Answers.Add(new Answer { reply = r }));
               db.Attendee.Add(regData.Attendee);                             
               db.SaveChanges();              
            }

            #region email format
            //what then email is supposed to look like
            /*Hello <firstname>,
 
             Thank you for registering for the <eventname> on <eventdate>.
 
             <Custom text> (I would like to be able to put this custome text in when creating the event).
 
             We look forward to seeing you there!
 
             CTS */
            #endregion

           //TODO: send confirmation email
            MailMessage msg = new MailMessage();
            msg.To.Add(regData.Attendee.Email);
            msg.Subject = "CTS - Registration Completed";
            msg.From = new MailAddress(WebConfigurationManager.AppSettings["SmtpSender"].ToString());
            msg.IsBodyHtml = true;
            msg.Body = "<div style='font-face: Segoe UI'>Hello " + regData.Attendee.FirstName + ",<br/><br/>" +
             "Thank you for registering for the " + regData.Event.Name + " on " + regData.Event.EventDate.ToString("MM/dd/yyyy") + " at " + regData.Event.EventDate.ToString("h:mm tt") + "<br/><br/>" +
             regData.Event.Texts + "<br/><br/>" +
             "We look forward to seeing you there! <br/><br/>" +
             "CTS</div>";

            SmtpClient smtp = new SmtpClient("PRDCASBHM01.askcts.com");
            smtp.UseDefaultCredentials = false;
            smtp.Send(msg);

            return View("Confirm", regData);
        }   

        //
        // GET: /Attendee/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Attendee Attendee = db.Attendee.Find(id);
            if (Attendee == null)
            {
                return HttpNotFound();
            }
            return View(Attendee);
        }

        //
        // POST: /Attendee/Edit/5

        [HttpPost]
        public ActionResult Edit(Attendee Attendee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(Attendee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Attendee);
        }

        //
        // GET: /Attendee/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Attendee Attendee = db.Attendee.Find(id);
            if (Attendee == null)
            {
                return HttpNotFound();
            }
            return View(Attendee);
        }

        //
        // POST: /Attendee/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int? id)
        {
            Attendee Attendee = db.Attendee.Find(id);
            db.Attendee.Remove(Attendee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //protected override void Dispose(bool disposing)
        //{
        //    db.Dispose();
        //    base.Dispose(disposing);
        //}
   //Random key to generate the key (this could be changed to something more cryptic 
    
       //
       //GET: /Attendee/Confirm
        public ActionResult Confirm(int? id)
        {
            Attendee attendees = db.Attendee.Find(id);
   
            return View(attendees);
        }

        public string RandomKey()
        {
            var chars = "ABCEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            var random = new Random();

            var UserKey = new string(
                Enumerable.Repeat(chars, 10)
                .Select(s => s[random.Next(s.Length)])
                .ToArray());
            return UserKey;
        }
    }
}

RSVPSite/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Cts.HR.Recruiting.RSVP.Models;
using Cts.HR.Recruiting.RSVP.ViewModels;
using Cts.HR.Recruiting.RSVP.Filters;

namespace Cts.HR.Recruiting.RSVP.Controllers
{
   [InitializeSimpleMembership]
   [Authorize]
    public class EventController : Controller
    {
        private RSVPDBContext db = new RSVPDBContext();

        //
        // GET: /Event/

        public ActionResult Index()
        {
           //var model = db.Events.Select(e => new ViewModels.EventData { Event = e })
           //    .ToList();

           //var viewModel = db.Events.Include(e => e.EventType).Select(a => new ViewModels.EventData {Event = a, EventTypes = db.EventTypes, UserProfile = a.Admin}).ToList();
           //viewModel.OrderByDescending(i => i.Event.EventDate);

           var model = db.Events.Include(e => e.EventType).Include(a => a.Admin).ToList();

            return View(model);
        }

        //
        // GET: /Event/Details/5

       [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
           Event Event = db.Events.Include(t => t.EventType).FirstOrDefault(e => e.Id == id);
            if (Event == null)
            {
                return HttpNotFound();
            }
            return View(Event);
        }

        //
        // GET: /Event/Create

        public ActionResult Create()
        {
           //TODO: input validations

           // MembershipUser user = Membership.GetUser(User.Identity.Name);
           //UserProfile admin = db.UserProfiles.Find(user.ProviderUserKey);
           var viewModel = new ViewModels.EventData
           {
              EventTypes = db.EventTypes
              //Event = new Event { Admin = admin }
           };
        
            return View(viewModel);
         }

        //
        // POST: /Event/Create

        /// <summary>Reminder - explanation of model types used here. viewmodel, which contains multiple models, is passed from the view.
        /// if data passed from view doesn't match the model (like data types), ModelState.IsValid will return false.
        /// at db.SaveChanges() spit error when eventtypeid was not passed to EventData.Event, because DDL was used instead of DDLFor 
        /// </summary>
        /// <requirements>must pass required data specified in model</requirements>
        /// <author>Yosuke</author>
        /// <date>4/9/2013</date>
        /// <exception></exception>
        /// <return></return>
        /// <param name="eventData"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(ViewModels.EventData eventData)
        {
            MembershipUser user = Membership.GetUser(User.Identity.Name);
            UserProfile admin = db.UserProfiles.Find(user.ProviderUserKey);
            int adminId = admin.UserId;
            eventData.Event.AdminId = adminId;

            //eventData.Event.AdminId = eventData.Event.Admin.UserId;

            var errors = ModelState.Values.Where(a => a.Errors.Any());

            if (ModelState.IsValid)
            {
                //eventData.CustomQuestions.ForEach(q => eventData.Event.CustomQuestions.Add(new CustomQuestion{Question=q}));
                //eventData.Event.CustomQuestions.add

                //get eventdata.event just inserted from the db, use the pk of that store the q into db

                #region alternate method for storing questions -yosuke
                //foreach (string q in eventData.CustomQuestions)
                //{
                //   if (string.IsNullOrWhiteSpace(q) == false)
                //   {
                //      eventData.Question.Question = q;
                //      eventData.Question.EventID = id;
                //      db.Questions.Add(eventData.Question);
                //   }
                //}
                #endregion


                #region questions (initial attempt) yosuke
                //if (string.IsNullOrWhiteSpace(eventData.Question.Question) == false)
                //{
                //   db.Questions.Add(eventData.Question);

                //   db.SaveChanges();//saving data causes ID creation, which is used as FK when inserting custom quesitons below

                //   foreach (string q in eventData.CustomQuestions)//pulling questions 2-5 which stored into list 
                //   {
                //      if (string.IsNullOrWhiteSpace(q) == false)
                //      {
                //         eventData.Question.Question = q;
                //         db.Questions.Add(eventData.Question);//eventData.Question already contains PK, allowing new custom question to be inserted here
                //         db.SaveChanges();
                //      }
                //   }
                //}
                //else if (eventData.CustomQuestions.Count > 0)
                //{
                //   db.SaveChanges();
                //   int id = eventData.Event.Id;
                //   foreach (string q in eventData.CustomQuestions)
                //   {
                //      if (string.IsNullOrWhiteSpace(q) == false)
                //      {
                //         eventData.Question.EventID = id;
                //         eventData.Question.Question = q;
                //         db.Questions.Add(eventData.Question);//eventData.Question already contains PK, allowing new custom question to be inserted here
                //         db.SaveChanges();
                //      }
                //   }
                //}
                #endregion

                db.Events.Add(eventData.Event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(); //TODO: model is not valid, do exception handling here. display error message on create?
        }

        //
        // GET: /Event/Edit/5

        public ActionResult Edit(int id = 0)
        {
           #region edit question scott
           //Event Event = db.Events.Find(id);
           
            //    CustomQuestion Question = db.Questions.Find(id);
       
            //if ((Event == null) || (Question == null)) 
            //{
            //    return HttpNotFound();
            //}     
            
            
            //this.ViewBag.CustomQuestionID = new SelectList(this.db.Questions, "CustomQuestionID", "Question", Question.CustomQuestionID);
           //this.ViewBag.Id = new SelectList(this.db.Events, "Id", "Name", Event.Id);
           #endregion

           //var viewModel = new ViewModels.EditEventData
           //{
           //   //Event = db.Events.Find(id),
           //   Event = db.Events.Include( e => e.CustomQuestions).SingleOrDefault( e => e.Id == id),
           //   EventTypes = db.EventTypes
           //};  
           //Event model = new Event();
           //model = db.Events.Find(id);

           var viewModel = new ViewModels.EditEventData
           {
              Event = db.Events.Find(id),
              EventTypes = db.EventTypes
           };
           
           return View(viewModel);
        }

        #region edit questions scott
        //added by scott 4-20 testing views/edits
        //public ActionResult EditQuestion(int id = 0)
        //{
         
        //    CustomQuestion Question = db.Questions.Find(id);

        //  if (Question == null)
        //    {
        //        return HttpNotFound();
        //    }

        //                this.ViewBag.CustomQuestionID = new SelectList(this.db.Questions, "CustomQuestionID", "Question", Question.CustomQuestionID);

        //                return View();
        //}
        #endregion
        //
        // POST: /Event/Edit/5

        [HttpPost]
        public ActionResult Edit(EditEventData postData)
        {
           MembershipUser user = Membership.GetUser(User.Identity.Name);
           UserProfile admin = db.UserProfiles.Find(user.ProviderUserKey);
           int adminId = admin.UserId;
           postData.Event.AdminId = adminId;

           var errors = ModelState.Values.Where(a => a.Errors.Any());

           //TODO: try foreach to remove customquestions from db then re-enter customquestion values of event 

           //foreach (CustomQuestion q in postData.Event.CustomQuestions)
           //{
           //   int id = q.CustomQuestionID;
           //   CustomQuestion cq = db.Questions.Find(id);
           //   db.Questions.Remove(cq);
           //   db.Questions.Add(q);              
           //}
           db.SaveChanges();

           if (ModelState.IsValid)
           {
              db.Entry(postData.Event).State = EntityState.Modified;
              db.SaveChanges();
              return RedirectToAction("Index");
           }
 
         return View(postData); //TODO: display error
        }

        //
        // GET: /Event/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Event Event = db.Events.Find(id);
            if (Event == null)
            {
                return HttpNotFound();
            }
            return View(Event);
        }

        //
        // POST: /Event/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Event Event = db.Events.Find(id);
            db.Events.Remove(Event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}


RSVPSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - RSVP</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")

        <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
        @RenderSection("Content", false)

        <link href="~/Content/themes/base/jquery.ui.all.css" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.7.2.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-1.7.2.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.20.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-TimePicker-1.0.0.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/Site.js")" type="text/javascript"></script>
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.core.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.datepicker.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery-ui.css")" rel="stylesheet" type="text/css" />

        @*<link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />*@
   
        
         </head>

    <body>

                @* Facebook *@
        <div id="fb-root"></div>
        <script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
        
        
             @* Twitter *@
        <script>!function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0]; if (!d.getElementById(id)) {
        js = d.createElement(s);
        js.id = id; js.src = "https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js, fjs);
    }
}(document, "script", "twitter-wjs");</script>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <a href="~/Home/Index"><img src="~/Images/cts_logo.png" /> </a>
                    @*<p class="site-title">@Html.ActionLink("CTS", "Index", "Home")</p>*@
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                          @if (User.Identity.IsAuthenticated == true) { 
                            <li>@Html.ActionLink("Events","Index","Event")</li>
                            <li>@Html.ActionLink("Create","Create", "Event")</li>                          
                            <li>@Html.ActionLink("Admin","Register","Account")</li>
                            @*<li>@Html.ActionLink("Excel", "Excel", "Attendee")</li>*@  
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
         <div class="socialmedia">
   
             @* Facebook *@
        <div class="fb-like" data-href="https://www.facebook.com/askCTS" data-send="true" data-width="200" data-show-faces="true"></div>
   <br /><br />
            @* Twitter *@
        <a href="https://twitter.com/intent/tweet?screen_name=askCTS" class="twitter-mention-button" data-lang="en">Tweet to @@askCTS</a>
      </div>
          <footer>
             

            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year Computer Technology Solutions</p>
                </div>
            </div>
        </footer>

        @RenderSection("scripts", required: false)
    </body>
</html>